version: '3'
services:
  web:
    build: .
    command: python ./main.py
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      TEST_ENV: abc
  terminal:
    build: .
    command: python ./src/terminal/main_terminal.py
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      TEST_ENV: abc